version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_password 
      - MYSQL_DATABASE=todo_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ../backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=your_password 
      - DB_NAME=todo_db
  frontend:
    build: ../frontend
    ports:
      - "5173:5173"  
    depends_on:
      - backend
    environment:
    - VITE_API_URL=http://backend:3000/api